/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GradientButton {
        "fromColor": string;
        "label": string;
        "size"?: 'sm' | 'md' | 'lg';
        "theme": 'dark' | 'light';
        "toColor": string;
    }
    interface GradientInput {
        "fromColor": string;
        "invalid"?: boolean;
        "label": string;
        "placeholder": string;
        "toColor": string;
        "variant"?: 'lined' | 'outlined';
    }
}
declare global {
    interface HTMLGradientButtonElement extends Components.GradientButton, HTMLStencilElement {
    }
    var HTMLGradientButtonElement: {
        prototype: HTMLGradientButtonElement;
        new (): HTMLGradientButtonElement;
    };
    interface HTMLGradientInputElement extends Components.GradientInput, HTMLStencilElement {
    }
    var HTMLGradientInputElement: {
        prototype: HTMLGradientInputElement;
        new (): HTMLGradientInputElement;
    };
    interface HTMLElementTagNameMap {
        "gradient-button": HTMLGradientButtonElement;
        "gradient-input": HTMLGradientInputElement;
    }
}
declare namespace LocalJSX {
    interface GradientButton {
        "fromColor"?: string;
        "label"?: string;
        "size"?: 'sm' | 'md' | 'lg';
        "theme"?: 'dark' | 'light';
        "toColor"?: string;
    }
    interface GradientInput {
        "fromColor"?: string;
        "invalid"?: boolean;
        "label"?: string;
        "placeholder"?: string;
        "toColor"?: string;
        "variant"?: 'lined' | 'outlined';
    }
    interface IntrinsicElements {
        "gradient-button": GradientButton;
        "gradient-input": GradientInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gradient-button": LocalJSX.GradientButton & JSXBase.HTMLAttributes<HTMLGradientButtonElement>;
            "gradient-input": LocalJSX.GradientInput & JSXBase.HTMLAttributes<HTMLGradientInputElement>;
        }
    }
}
